-- Minecraft Java protocol dissector for Wireshark, driven by PrismarineJS/minecraft-data
--
-- Decodes unencrypted Minecraft TCP traffic (1.8+, offline-mode or LAN servers, or the
-- client <-> SniffCraft leg of a SniffCraft session) with the protocol definitions
-- generated by tools/gen_mcdata.py in the minecraft_mcdata folder next to this file.
-- Online-mode traffic is encrypted after login and can't be read here, capture it
-- with the SniffCraft extcap instead.
--
-- It also exposes minecraft_native.dissect_packet, used by sniffcraft.lua to show an
-- independent parse of each packet captured by SniffCraft.
--
-- Install: copy this file and the minecraft_mcdata folder to the personal Lua plugins
-- folder (Help > About Wireshark > Folders), e.g. %APPDATA%\Wireshark\plugins
--
-- Needs Wireshark 4.4 or newer (Lua 5.3+ integers and bitwise operators)

set_plugin_info({
    version = "1.0.0",
    description = "Minecraft Java protocol dissector (minecraft-data definitions)",
    author = "SniffCraft-Wireshark contributors",
    repository = "https://github.com/dioxtra/SniffCraft-Wireshark",
})

local minecraft = Proto("minecraft", "Minecraft Java")

-- Same values as ProtocolCraft::ConnectionState, also used by sniffcraft.lua
local STATE_HANDSHAKE, STATE_STATUS, STATE_LOGIN, STATE_PLAY, STATE_CONFIGURATION = 0, 1, 2, 3, 4
local state_keys = { [0] = "handshaking", [1] = "status", [2] = "login", [3] = "play", [4] = "configuration" }
local state_names = { [0] = "Handshake", [1] = "Status", [2] = "Login", [3] = "Play", [4] = "Configuration" }

-- First protocol version with the configuration state (1.20.2)
local PROTOCOL_WITH_CONFIGURATION = 764

-- Array elements shown in the tree, the others are parsed but not displayed
local MAX_TREE_ELEMENTS = 256
local MAX_DEPTH = 100
local MAX_STRING_DISPLAY = 512

local pf = minecraft.fields
pf.length = ProtoField.uint32("minecraft.length", "Packet length", base.DEC)
pf.data_length = ProtoField.uint32("minecraft.data_length", "Uncompressed length", base.DEC)
pf.packet_id = ProtoField.int32("minecraft.packet_id", "Packet id", base.DEC)
pf.packet_name = ProtoField.string("minecraft.packet_name", "Packet name")
pf.state = ProtoField.uint8("minecraft.state", "State", base.DEC, state_names)
pf.direction = ProtoField.string("minecraft.direction", "Direction")
pf.protocol_version = ProtoField.uint32("minecraft.protocol_version", "Protocol version", base.DEC)
pf.definition = ProtoField.string("minecraft.definition", "Definition")
pf.field = ProtoField.string("minecraft.field", "Field")
pf.field_path = ProtoField.string("minecraft.field.path", "Field path")
pf.summary = ProtoField.string("minecraft.summary", "Summary")
pf.data = ProtoField.bytes("minecraft.data", "Data")

local ef = {
    encrypted = ProtoExpert.new("minecraft.encrypted", "Encrypted (online-mode) data, capture with the SniffCraft extcap to see it",
        expert.group.UNDECODED, expert.severity.NOTE),
    error = ProtoExpert.new("minecraft.error", "Parsing error", expert.group.MALFORMED, expert.severity.WARN),
    leftover = ProtoExpert.new("minecraft.leftover", "Bytes not covered by the definition", expert.group.MALFORMED, expert.severity.WARN),
    unknown_packet = ProtoExpert.new("minecraft.unknown_packet", "Unknown packet id", expert.group.MALFORMED, expert.severity.WARN),
    fallback = ProtoExpert.new("minecraft.definition.fallback", "Definition of another protocol version used",
        expert.group.PROTOCOL, expert.severity.NOTE),
    no_definition = ProtoExpert.new("minecraft.definition.missing", "No protocol definition", expert.group.UNDECODED, expert.severity.WARN),
    no_handshake = ProtoExpert.new("minecraft.no_handshake", "Handshake not captured, state and protocol version are guessed",
        expert.group.SEQUENCE, expert.severity.NOTE),
}
minecraft.experts = { ef.encrypted, ef.error, ef.leftover, ef.unknown_packet, ef.fallback, ef.no_definition, ef.no_handshake }

minecraft.prefs.ports = Pref.range("TCP ports", "25565,25555",
    "TCP ports decoded as Minecraft (25555 is the default SniffCraft proxy port)", 65535)
minecraft.prefs.default_protocol = Pref.uint("Protocol version without handshake", 0,
    "Protocol version used when the handshake wasn't captured, 0 for the newest available definition")

---------------------------------------------------------------------------
-- Protocol definitions
---------------------------------------------------------------------------

local data_dir = (debug.getinfo(1, "S").source:match("^@(.*[/\\])") or "") .. "minecraft_mcdata" .. package.config:sub(1, 1)
local index = nil
local definitions = {}

local function load_index()
    if index == nil then
        local chunk = loadfile(data_dir .. "index.mcdata")
        index = chunk and chunk() or { protocols = {} }
        index.versions = index.versions or {}
    end
    return index
end

-- "1.21.9 - 1.21.10" for protocol 773, nil if unknown
local function version_name(protocol_version)
    return load_index().versions[protocol_version]
end

local function newest_protocol()
    local newest = nil
    for protocol in pairs(load_index().protocols) do
        if newest == nil or protocol > newest then
            newest = protocol
        end
    end
    return newest
end

-- Returns the definition for a protocol version (or the closest older one), the protocol
-- version it was generated for and the definition name
local function get_definition(protocol_version)
    local protocols = load_index().protocols
    local used = protocol_version
    if protocols[used] == nil then
        used = nil
        for protocol in pairs(protocols) do
            if protocol <= protocol_version and (used == nil or protocol > used) then
                used = protocol
            end
        end
        if used == nil then
            return nil
        end
    end
    local name = protocols[used]
    if definitions[name] == nil then
        local chunk = loadfile(data_dir .. name .. ".mcdata")
        definitions[name] = chunk and chunk() or false
    end
    return definitions[name] or nil, used, name
end

-- Packet id -> name for a "packet" mapper, cached per mapping table
local mapping_cache = setmetatable({}, { __mode = "k" })

local function lookup_mapping(mappings, value)
    local cache = mapping_cache[mappings]
    if cache == nil then
        cache = {}
        for k, v in pairs(mappings) do
            cache[tonumber(k) or k] = v
        end
        mapping_cache[mappings] = cache
    end
    return cache[value]
end

---------------------------------------------------------------------------
-- Generic reader for minecraft-data (ProtoDef) types
---------------------------------------------------------------------------

-- Key of the parent context in container contexts (used by "../field" references)
local PARENT = {}

local Reader = {}
Reader.__index = Reader

local function new_reader(tvb, definition, state_types)
    return setmetatable({
        tvb = tvb,
        pos = 0,
        len = tvb:len(),
        global_types = definition.types,
        state_types = state_types or {},
        depth = 0,
        mask_top_bit = false,
    }, Reader)
end

local function child_path(path, name)
    if name:sub(1, 1) == "[" or path == "" then
        return path .. name
    end
    return path .. "." .. name
end

local function resolve_path(ctx, path)
    local current = ctx
    for part in path:gmatch("[^/]+") do
        if type(current) ~= "table" then
            return nil
        end
        if part == ".." then
            current = current[PARENT]
        else
            current = current[part]
        end
    end
    return current
end

local function value_key(value)
    if type(value) == "number" and math.type(value) == "float" and value == math.floor(value) then
        return string.format("%d", value)
    end
    return tostring(value)
end

-- string.format follows the locale Wireshark runs with, which can use a decimal comma
local function format_float(value, digits)
    return (string.format("%." .. digits .. "g", value):gsub(",", "."))
end

local function display_string(s)
    if #s > MAX_STRING_DISPLAY then
        s = s:sub(1, MAX_STRING_DISPLAY) .. "..."
    end
    return '"' .. s .. '"'
end

function Reader:need(n)
    if n < 0 or self.pos + n > self.len then
        error(string.format("%d byte(s) needed at offset %d, %d available", n, self.pos, self.len - self.pos), 0)
    end
end

function Reader:u8()
    self:need(1)
    local value = self.tvb(self.pos, 1):uint()
    self.pos = self.pos + 1
    return value
end

function Reader:peek_u8()
    self:need(1)
    return self.tvb(self.pos, 1):uint()
end

function Reader:var(max_bytes)
    local value, shift = 0, 0
    for _ = 1, max_bytes do
        local b = self:u8()
        value = value | ((b & 0x7F) << shift)
        if (b & 0x80) == 0 then
            if max_bytes == 5 then
                value = value & 0xFFFFFFFF
                if value >= 0x80000000 then
                    value = value - 0x100000000
                end
            end
            return value
        end
        shift = shift + 7
    end
    error("varint too long", 0)
end

-- Add a value covering the bytes read since start
function Reader:add(tree, name, path, start, text)
    if tree == nil then
        return nil
    end
    local label = name ~= nil and name ~= "" and (name .. ": " .. text) or text
    local item
    if self.pos > start then
        item = tree:add(pf.field, self.tvb(start, self.pos - start), label)
    else
        item = tree:add(pf.field, label)
    end
    item:set_text(label)
    if path ~= "" then
        item:add(pf.field_path, path):set_hidden()
    end
    return item
end

-- Open a sub tree, closed with Reader:close once its content is read
function Reader:open(tree, name, path)
    if tree == nil then
        return nil
    end
    local item
    if self.pos < self.len then
        item = tree:add(pf.field, self.tvb(self.pos, self.len - self.pos), name)
    else
        item = tree:add(pf.field, name)
    end
    item:set_text(name)
    if path ~= "" then
        item:add(pf.field_path, path):set_hidden()
    end
    return item
end

function Reader:close(item, start, text)
    if item == nil then
        return
    end
    if start < self.len then
        item:set_len(self.pos - start)
    end
    if text ~= nil then
        item:set_text(text)
    end
end

function Reader:count(args, ctx)
    if args.count ~= nil then
        if type(args.count) == "number" then
            return args.count
        end
        local count = resolve_path(ctx, args.count)
        if math.type(count) ~= "integer" then
            error("invalid count reference " .. tostring(args.count), 0)
        end
        return count
    end
    return self:read(args.countType, nil, nil, ctx, "")
end

local natives = {}

-- Replace the "$name" parameters of a custom type definition with their values
local function substitute(definition, params)
    if type(definition) == "string" then
        if definition:sub(1, 1) == "$" and params[definition:sub(2)] ~= nil then
            return params[definition:sub(2)]
        end
        return definition
    end
    if type(definition) == "table" then
        local copy = {}
        for k, v in pairs(definition) do
            copy[k] = substitute(v, params)
        end
        return copy
    end
    return definition
end

-- Parametrized type reference -> its definition with the parameters replaced
local expanded_types = setmetatable({}, { __mode = "k" })

function Reader:resolve_type(typ)
    while true do
        local kind, args = typ, nil
        if type(typ) == "table" then
            kind, args = typ[1], typ[2]
        end
        local definition = self.state_types[kind]
        if definition == nil then
            definition = self.global_types[kind]
        end
        if definition == nil or definition == "native" then
            if natives[kind] == nil then
                error("unsupported type " .. tostring(kind), 0)
            end
            return kind, args
        end
        if args == nil then
            typ = definition
        else
            -- Custom type used with parameters, like ["entityMetadataItem", {"compareTo": "type"}]
            local expanded = expanded_types[typ]
            if expanded == nil then
                expanded = substitute(definition, args)
                expanded_types[typ] = expanded
            end
            typ = expanded
        end
    end
end

-- Read a value, add it to tree (when not nil) and return it
-- ctx: values of the container being read, for field references
-- anon: merge container fields in ctx and tree instead of creating a sub element
function Reader:read(typ, name, tree, ctx, path, anon)
    self.depth = self.depth + 1
    if self.depth > MAX_DEPTH then
        error("type nesting too deep", 0)
    end
    local kind, args = self:resolve_type(typ)
    if natives[kind] == nil then
        error("unsupported type " .. tostring(kind), 0)
    end
    local value = natives[kind](self, args, name, tree, ctx, path, anon)
    self.depth = self.depth - 1
    return value
end

local function integer_type(size, signed)
    return function(r, _, name, tree, _, path)
        r:need(size)
        local start = r.pos
        local value, text
        if size == 8 then
            local range = r.tvb(start, 8)
            value = (range:range(0, 4):uint() << 32) | range:range(4, 4):uint()
            text = signed and tostring(value) or tostring(range:uint64())
        else
            local range = r.tvb(start, size)
            value = signed and range:int() or range:uint()
            if size == 1 and r.mask_top_bit then
                value = value & 0x7F
            end
            text = tostring(value)
        end
        r.mask_top_bit = false
        r.pos = r.pos + size
        r:add(tree, name, path, start, text)
        return value
    end
end

natives.u8 = integer_type(1, false)
natives.i8 = integer_type(1, true)
natives.u16 = integer_type(2, false)
natives.i16 = integer_type(2, true)
natives.u32 = integer_type(4, false)
natives.i32 = integer_type(4, true)
natives.u64 = integer_type(8, false)
natives.i64 = integer_type(8, true)

local function float_type(size)
    return function(r, _, name, tree, _, path)
        r:need(size)
        local start = r.pos
        local value = r.tvb(start, size):float()
        r.pos = r.pos + size
        r:add(tree, name, path, start, format_float(value, 7))
        return value
    end
end

natives.f32 = float_type(4)
natives.f64 = float_type(8)

natives.bool = function(r, _, name, tree, _, path)
    local start = r.pos
    local value = r:u8() ~= 0
    r:add(tree, name, path, start, tostring(value))
    return value
end

natives.varint = function(r, _, name, tree, _, path)
    local start = r.pos
    local value = r:var(5)
    r:add(tree, name, path, start, tostring(value))
    return value
end

natives.varlong = function(r, _, name, tree, _, path)
    local start = r.pos
    local value = r:var(10)
    r:add(tree, name, path, start, tostring(value))
    return value
end

natives.UUID = function(r, _, name, tree, _, path)
    r:need(16)
    local start = r.pos
    local hex = tostring(r.tvb(start, 16):bytes()):lower()
    r.pos = r.pos + 16
    local value = hex:sub(1, 8) .. "-" .. hex:sub(9, 12) .. "-" .. hex:sub(13, 16) .. "-" .. hex:sub(17, 20) .. "-" .. hex:sub(21, 32)
    r:add(tree, name, path, start, value)
    return value
end

natives.pstring = function(r, args, name, tree, ctx, path)
    local start = r.pos
    local size = r:count(args, ctx)
    r:need(size)
    local value = size > 0 and r.tvb(r.pos, size):string(ENC_UTF_8) or ""
    r.pos = r.pos + size
    r:add(tree, name, path, start, display_string(value))
    return value
end

local function add_bytes(r, tree, name, path, start, size)
    local text = string.format("%d byte%s", size, size == 1 and "" or "s")
    if size > 0 and size <= 32 then
        text = text .. " (" .. tostring(r.tvb(r.pos - size, size):bytes()):lower() .. ")"
    end
    r:add(tree, name, path, start, text)
end

natives.buffer = function(r, args, name, tree, ctx, path)
    local start = r.pos
    local size = r:count(args, ctx)
    r:need(size)
    r.pos = r.pos + size
    add_bytes(r, tree, name, path, start, size)
    return size
end

natives.restBuffer = function(r, _, name, tree, _, path)
    local start = r.pos
    local size = r.len - r.pos
    r.pos = r.len
    add_bytes(r, tree, name, path, start, size)
    return size
end

natives.void = function()
    return nil
end

natives.option = function(r, args, name, tree, ctx, path)
    local start = r.pos
    if r:u8() == 0 then
        r:add(tree, name, path, start, "(absent)")
        return nil
    end
    return r:read(args, name, tree, ctx, path)
end

natives.container = function(r, fields, name, tree, ctx, path, anon)
    local start = r.pos
    local own_ctx, item = ctx, tree
    if not anon then
        own_ctx = { [PARENT] = ctx }
        item = r:open(tree, name or "", path)
    end
    for _, field in ipairs(fields) do
        if field.anon then
            -- Anonymous containers are merged by the read, other anonymous values (bitfields) here
            local value = r:read(field.type, nil, item, own_ctx, path, true)
            if type(value) == "table" and value ~= own_ctx then
                for k, v in pairs(value) do
                    if k ~= PARENT then
                        own_ctx[k] = v
                    end
                end
            end
        else
            own_ctx[field.name] = r:read(field.type, field.name, item, own_ctx, child_path(path, field.name))
        end
    end
    if not anon then
        r:close(item, start)
    end
    return own_ctx
end

natives.switch = function(r, args, name, tree, ctx, path, anon)
    local key = value_key(resolve_path(ctx, args.compareTo))
    local chosen = args.fields[key]
    if chosen == nil then
        chosen = args.default or "void"
    end
    return r:read(chosen, name, tree, ctx, path, anon)
end

natives.mapper = function(r, args, name, tree, ctx, path)
    local start = r.pos
    local raw = r:read(args.type, nil, nil, ctx, "")
    local mapped = lookup_mapping(args.mappings, raw)
    r:add(tree, name, path, start, string.format("%s (%s)", mapped or "unknown", tostring(raw)))
    if mapped == nil then
        return raw
    end
    return mapped
end

local function check_count(r, count)
    -- Each element takes at least one byte in practice, refuse obviously broken counts
    if count < 0 or count > r.len - r.pos + 1024 then
        error("invalid element count " .. tostring(count), 0)
    end
end

natives.array = function(r, args, name, tree, ctx, path)
    local start = r.pos
    local count = r:count(args, ctx)
    check_count(r, count)
    local item = r:open(tree, name or "", path)
    local values = {}
    for i = 1, count do
        local element_name = "[" .. (i - 1) .. "]"
        values[i] = r:read(args.type, element_name, i <= MAX_TREE_ELEMENTS and item or nil, ctx, path .. element_name)
    end
    if item ~= nil and count > MAX_TREE_ELEMENTS then
        item:add(pf.field, string.format("... %d more", count - MAX_TREE_ELEMENTS))
    end
    r:close(item, start, string.format("%s (%d element%s)", name or "", count, count == 1 and "" or "s"))
    return values
end

natives.bitfield = function(r, fields, name, tree, _, path)
    local total_bits = 0
    for _, field in ipairs(fields) do
        total_bits = total_bits + field.size
    end
    local size = total_bits // 8
    r:need(size)
    local start = r.pos
    local bits = 0
    for i = 0, size - 1 do
        bits = (bits << 8) | r.tvb(start + i, 1):uint()
    end
    r.pos = r.pos + size

    local values, parts = {}, {}
    local shift = total_bits
    for _, field in ipairs(fields) do
        shift = shift - field.size
        local value = (bits >> shift) & ((1 << field.size) - 1)
        if field.signed and value >= (1 << (field.size - 1)) then
            value = value - (1 << field.size)
        end
        values[field.name] = value
        parts[#parts + 1] = field.name .. "=" .. value
    end
    local item = r:add(tree, name, path, start, table.concat(parts, ", "))
    if item ~= nil then
        for _, field in ipairs(fields) do
            item:add(pf.field, r.tvb(start, size), field.name .. ": " .. values[field.name])
                :set_text(field.name .. ": " .. values[field.name])
        end
    end
    return values
end

natives.bitflags = function(r, args, name, tree, ctx, path)
    local start = r.pos
    local raw = r:read(args.type, nil, nil, ctx, "")
    local masks = {}
    if args.flags[1] ~= nil then
        for i, flag in ipairs(args.flags) do
            masks[flag] = 1 << (i - 1)
        end
    else
        for flag, mask in pairs(args.flags) do
            masks[flag] = args.shift and (1 << mask) or mask
        end
    end
    local values, set = { _value = raw }, {}
    for flag, mask in pairs(masks) do
        values[flag] = (raw & mask) == mask
        if values[flag] then
            set[#set + 1] = flag
        end
    end
    table.sort(set)
    r:add(tree, name, path, start, string.format("0x%x (%s)", raw, table.concat(set, ", ")))
    return values
end

natives.entityMetadataLoop = function(r, args, name, tree, ctx, path)
    local start = r.pos
    local item = r:open(tree, name or "", path)
    local values = {}
    while r:peek_u8() ~= args.endVal do
        local element_name = "[" .. #values .. "]"
        values[#values + 1] = r:read(args.type, element_name, item, ctx, path .. element_name)
    end
    r.pos = r.pos + 1
    r:close(item, start, string.format("%s (%d entries)", name or "", #values))
    return values
end

natives.topBitSetTerminatedArray = function(r, args, name, tree, ctx, path)
    local start = r.pos
    local item = r:open(tree, name or "", path)
    local values = {}
    repeat
        local first = r:peek_u8()
        local element_name = "[" .. #values .. "]"
        -- The top bit of the element first byte only tells if another element follows
        r.mask_top_bit = true
        values[#values + 1] = r:read(args.type, element_name, item, ctx, path .. element_name)
        r.mask_top_bit = false
    until (first & 0x80) == 0
    r:close(item, start, string.format("%s (%d element%s)", name or "", #values, #values == 1 and "" or "s"))
    return values
end

natives.registryEntryHolder = function(r, args, name, tree, ctx, path)
    local start = r.pos
    local id = r:var(5)
    if id ~= 0 then
        r:add(tree, name, path, start, args.baseName .. " = " .. (id - 1))
        return { [args.baseName] = id - 1 }
    end
    local item = r:open(tree, name or "", path)
    local own_ctx = { [PARENT] = ctx }
    own_ctx[args.otherwise.name] = r:read(args.otherwise.type, args.otherwise.name, item, own_ctx,
        child_path(path, args.otherwise.name))
    r:close(item, start)
    return own_ctx
end

natives.registryEntryHolderSet = function(r, args, name, tree, ctx, path)
    local start = r.pos
    local count = r:var(5)
    if count == 0 then
        local value = r:read(args.base.type, nil, nil, ctx, "")
        r:add(tree, name, path, start, args.base.name .. " = " .. tostring(value))
        return { [args.base.name] = value }
    end
    check_count(r, count - 1)
    local ids, texts = {}, {}
    for i = 1, count - 1 do
        ids[i] = r:read(args.otherwise.type, nil, nil, ctx, "")
        if i <= 32 then
            texts[i] = tostring(ids[i])
        end
    end
    r:add(tree, name, path, start, args.otherwise.name .. " = [" .. table.concat(texts, ", ") .. (count - 1 > 32 and ", ...]" or "]"))
    return { [args.otherwise.name] = ids }
end

-- Low precision vector (entity velocities, 1.21.9+)
natives.lpVec3 = function(r, _, name, tree, _, path)
    local start = r.pos
    local a = r:u8()
    if a == 0 then
        r:add(tree, name, path, start, "(0, 0, 0)")
        return { x = 0, y = 0, z = 0 }
    end
    local b = r:u8()
    r:need(4)
    local c = r.tvb(r.pos, 4):uint()
    r.pos = r.pos + 4
    local packed = (c << 16) | (b << 8) | a
    local scale = a & 3
    if (a & 4) == 4 then
        scale = scale + (r:var(5) & 0xFFFFFFFF) * 4
    end
    local function unpack(shift)
        return math.min((packed >> shift) & 0x7FFF, 32766) * 2.0 / 32766.0 - 1.0
    end
    local value = { x = unpack(3) * scale, y = unpack(18) * scale, z = unpack(33) * scale }
    r:add(tree, name, path, start, "(" .. format_float(value.x, 5) .. ", " .. format_float(value.y, 5) .. ", " .. format_float(value.z, 5) .. ")")
    return value
end

-- Network NBT (no root name, 1.20.2+)
local nbt_type_names = {
    [1] = "byte", [2] = "short", [3] = "int", [4] = "long", [5] = "float", [6] = "double", [7] = "byte array",
    [8] = "string", [9] = "list", [10] = "compound", [11] = "int array", [12] = "long array",
}

-- Returns the value: number, string, table for lists and compounds, element count for arrays
local function nbt_payload(r, tag, name, tree, path)
    r.depth = r.depth + 1
    if r.depth > MAX_DEPTH then
        error("NBT nesting too deep", 0)
    end
    local start = r.pos
    local value
    if tag >= 1 and tag <= 6 then
        local sizes = { 1, 2, 4, 8, 4, 8 }
        local size = sizes[tag]
        r:need(size)
        local range = r.tvb(start, size)
        local text
        if tag == 5 or tag == 6 then
            value = range:float()
            text = format_float(value, 7)
        elseif tag == 4 then
            local long = range:int64()
            value = long:tonumber()
            text = tostring(long)
        else
            value = range:int()
            text = tostring(value)
        end
        r.pos = r.pos + size
        r:add(tree, name, path, start, text)
    elseif tag == 7 or tag == 11 or tag == 12 then
        r:need(4)
        local count = r.tvb(r.pos, 4):int()
        r.pos = r.pos + 4
        local element_size = tag == 7 and 1 or (tag == 11 and 4 or 8)
        check_count(r, count)
        r:need(count * element_size)
        r.pos = r.pos + count * element_size
        value = count
        r:add(tree, name, path, start, string.format("%s [%d]", nbt_type_names[tag], count))
    elseif tag == 8 then
        r:need(2)
        local size = r.tvb(r.pos, 2):uint()
        r.pos = r.pos + 2
        r:need(size)
        value = size > 0 and r.tvb(r.pos, size):string(ENC_UTF_8) or ""
        r.pos = r.pos + size
        r:add(tree, name, path, start, display_string(value))
    elseif tag == 9 then
        r:need(5)
        local element_tag = r.tvb(r.pos, 1):uint()
        local count = r.tvb(r.pos + 1, 4):int()
        r.pos = r.pos + 5
        check_count(r, count)
        local item = r:open(tree, name, path)
        value = {}
        for i = 1, count do
            local element_name = "[" .. (i - 1) .. "]"
            value[i] = nbt_payload(r, element_tag, element_name, i <= MAX_TREE_ELEMENTS and item or nil, path .. element_name)
        end
        r:close(item, start, string.format("%s (list of %d %s)", name, count, nbt_type_names[element_tag] or "end"))
    elseif tag == 10 then
        local item = r:open(tree, name, path)
        local entries = 0
        value = {}
        while true do
            local child_tag = r:u8()
            if child_tag == 0 then
                break
            end
            r:need(2)
            local size = r.tvb(r.pos, 2):uint()
            r.pos = r.pos + 2
            r:need(size)
            local child_name = size > 0 and r.tvb(r.pos, size):string(ENC_UTF_8) or ""
            r.pos = r.pos + size
            value[child_name] = nbt_payload(r, child_tag, child_name, item, child_path(path, child_name))
            entries = entries + 1
        end
        r:close(item, start, string.format("%s (compound, %d entr%s)", name, entries, entries == 1 and "y" or "ies"))
    else
        error("invalid NBT tag " .. tag, 0)
    end
    r.depth = r.depth - 1
    return value
end

natives.anonymousNbt = function(r, _, name, tree, _, path)
    local start = r.pos
    local tag = r:u8()
    if tag == 0 then
        r:add(tree, name, path, start, "(empty NBT)")
        return nil
    end
    return nbt_payload(r, tag, name or "nbt", tree, path)
end

-- NBT with a root name (before 1.20.2), a TAG_End byte means no NBT
natives.nbt = function(r, _, name, tree, _, path)
    local start = r.pos
    local tag = r:u8()
    if tag == 0 then
        r:add(tree, name, path, start, "(no NBT)")
        return nil
    end
    r:need(2)
    local root_name_size = r.tvb(r.pos, 2):uint()
    r.pos = r.pos + 2
    r:need(root_name_size)
    r.pos = r.pos + root_name_size
    return nbt_payload(r, tag, name or "nbt", tree, path)
end

natives.optionalNbt = natives.nbt

natives.anonOptionalNbt = function(r, args, name, tree, ctx, path)
    local start = r.pos
    if r:peek_u8() == 0 then
        r.pos = r.pos + 1
        r:add(tree, name, path, start, "(absent)")
        return nil
    end
    return natives.anonymousNbt(r, args, name, tree, ctx, path)
end

---------------------------------------------------------------------------
-- Packet summaries (Info column and minecraft.summary)
---------------------------------------------------------------------------

local MAX_SUMMARY = 200

-- Minimal JSON decoder for text components and status responses, nil if invalid
local json_escapes = { ['"'] = '"', ["\\"] = "\\", ["/"] = "/", b = "\b", f = "\f", n = "\n", r = "\r", t = "\t" }

local function json_decode(s)
    local pos = 1
    local value

    local function skip()
        pos = s:find("[^ \t\r\n]", pos) or #s + 1
    end

    local function decode_string()
        pos = pos + 1
        local parts = {}
        while true do
            local i = s:find('["\\]', pos)
            if i == nil then
                error("unterminated string", 0)
            end
            parts[#parts + 1] = s:sub(pos, i - 1)
            if s:sub(i, i) == '"' then
                pos = i + 1
                return table.concat(parts)
            end
            local c = s:sub(i + 1, i + 1)
            if c == "u" then
                local code = tonumber(s:sub(i + 2, i + 5), 16) or 0xFFFD
                pos = i + 6
                if code >= 0xD800 and code <= 0xDBFF and s:sub(pos, pos + 1) == "\\u" then
                    local low = tonumber(s:sub(pos + 2, pos + 5), 16)
                    if low ~= nil and low >= 0xDC00 and low <= 0xDFFF then
                        code = 0x10000 + ((code - 0xD800) << 10) + (low - 0xDC00)
                        pos = pos + 6
                    end
                end
                parts[#parts + 1] = utf8.char(code)
            else
                parts[#parts + 1] = json_escapes[c] or c
                pos = i + 2
            end
        end
    end

    local function decode_list(close, read_element)
        pos = pos + 1
        skip()
        if s:sub(pos, pos) == close then
            pos = pos + 1
            return
        end
        while true do
            read_element()
            skip()
            local c = s:sub(pos, pos)
            pos = pos + 1
            if c == close then
                return
            elseif c ~= "," then
                error("invalid json", 0)
            end
        end
    end

    function value()
        skip()
        local c = s:sub(pos, pos)
        if c == "{" then
            local object = {}
            decode_list("}", function()
                skip()
                if s:sub(pos, pos) ~= '"' then
                    error("invalid json key", 0)
                end
                local key = decode_string()
                skip()
                if s:sub(pos, pos) ~= ":" then
                    error("invalid json", 0)
                end
                pos = pos + 1
                object[key] = value()
            end)
            return object
        elseif c == "[" then
            local array = {}
            decode_list("]", function()
                array[#array + 1] = value()
            end)
            return array
        elseif c == '"' then
            return decode_string()
        end
        for literal, result in pairs({ ["true"] = true, ["false"] = false, ["null"] = false }) do
            if s:sub(pos, pos + #literal - 1) == literal then
                pos = pos + #literal
                return result
            end
        end
        local number = s:match("^-?[%d.eE+-]+", pos)
        if number == nil then
            error("invalid json", 0)
        end
        pos = pos + #number
        return tonumber(number)
    end

    local ok, result = pcall(value)
    return ok and result or nil
end

-- Common translation keys, the others are shown as "key [arguments]"
local translations = {
    ["chat.type.text"] = "<%s> %s",
    ["chat.type.announcement"] = "[%s] %s",
    ["chat.type.emote"] = "* %s %s",
    ["chat.type.admin"] = "[%s: %s]",
    ["chat.type.team.text"] = "%s <%s> %s",
    ["chat.type.team.sent"] = "-> %s <%s> %s",
    ["chat.type.advancement.task"] = "%s has made the advancement %s",
    ["chat.type.advancement.challenge"] = "%s has completed the challenge %s",
    ["chat.type.advancement.goal"] = "%s has reached the goal %s",
    ["commands.message.display.incoming"] = "%s whispers to you: %s",
    ["commands.message.display.outgoing"] = "You whisper to %s: %s",
    ["multiplayer.player.joined"] = "%s joined the game",
    ["multiplayer.player.joined.renamed"] = "%s (formerly known as %s) joined the game",
    ["multiplayer.player.left"] = "%s left the game",
    ["multiplayer.disconnect.kicked"] = "Kicked by an operator",
    ["multiplayer.disconnect.server_shutdown"] = "Server closed",
    ["multiplayer.disconnect.duplicate_login"] = "You logged in from another location",
    ["multiplayer.disconnect.not_whitelisted"] = "You are not whitelisted on this server!",
    ["multiplayer.disconnect.server_full"] = "Server is full!",
    ["multiplayer.disconnect.outdated_client"] = "Incompatible client! Please use %s",
    ["multiplayer.disconnect.idling"] = "You have been idle for too long!",
    ["disconnect.timeout"] = "Timed out",
}

local component_text

local function format_translation(format, args)
    local next_arg = 0
    return (format:gsub("%%(%d*)%$?s", function(position)
        next_arg = next_arg + 1
        return args[tonumber(position) or next_arg] or ""
    end))
end

-- Plain text of a chat component (json decoded or NBT)
function component_text(component, depth)
    depth = depth or 0
    if depth > 16 then
        return ""
    end
    if type(component) == "string" then
        return component
    elseif type(component) == "number" then
        return tostring(component)
    elseif type(component) ~= "table" then
        return ""
    end
    local parts = {}
    if component[1] ~= nil and component.text == nil and component.translate == nil then
        -- List of components
        for _, child in ipairs(component) do
            parts[#parts + 1] = component_text(child, depth + 1)
        end
        return table.concat(parts)
    end
    parts[1] = component.text or component[""] or ""
    if type(component.translate) == "string" then
        local args = {}
        if type(component.with) == "table" then
            for i, arg in ipairs(component.with) do
                args[i] = component_text(arg, depth + 1)
            end
        end
        local format = translations[component.translate] or component.fallback
        if type(format) == "string" then
            parts[#parts + 1] = format_translation(format, args)
        else
            parts[#parts + 1] = component.translate .. (#args > 0 and (" [" .. table.concat(args, ", ") .. "]") or "")
        end
    end
    if type(component.extra) == "table" then
        for _, child in ipairs(component.extra) do
            parts[#parts + 1] = component_text(child, depth + 1)
        end
    end
    return table.concat(parts)
end

-- Text of a component sent as json (before 1.20.3 and in the login state) or as NBT
local function text_of(value)
    if type(value) == "string" then
        local first = value:sub(1, 1)
        if first == "{" or first == "[" or first == '"' then
            local decoded = json_decode(value)
            if decoded ~= nil then
                return component_text(decoded)
            end
        end
        return value
    end
    return component_text(value)
end

local function position_text(x, y, z)
    if type(x) ~= "number" or type(y) ~= "number" or type(z) ~= "number" then
        return nil
    end
    return string.format("%s %s %s", format_float(x, 7), format_float(y, 7), format_float(z, 7))
end

local next_states = { [1] = "status", [2] = "login", [3] = "transfer" }

-- Packet name -> function(values) returning a short description
local summarizers = {}

summarizers.set_protocol = function(v)
    local version = version_name(v.protocolVersion)
    return string.format("protocol %s%s, %s:%s, %s", tostring(v.protocolVersion), version and (" (" .. version .. ")") or "",
        tostring(v.serverHost):gsub("%z.*", ""), tostring(v.serverPort), next_states[v.nextState] or tostring(v.nextState))
end
summarizers.login_start = function(v) return v.username end
summarizers.success = function(v) return v.username end
summarizers.compress = function(v) return "threshold " .. tostring(v.threshold) end
summarizers.disconnect = function(v) return text_of(v.reason) end
summarizers.kick_disconnect = summarizers.disconnect
summarizers.system_chat = function(v)
    return text_of(v.content) .. ((v.isActionBar or v.overlay) and " [action bar]" or "")
end
summarizers.chat = function(v) return text_of(v.message) end
summarizers.chat_message = function(v) return v.message end
summarizers.chat_command = function(v) return "/" .. tostring(v.command) end
summarizers.chat_command_signed = summarizers.chat_command
summarizers.player_chat = function(v)
    local message = v.plainMessage
    if v.unsignedChatContent ~= nil then
        message = text_of(v.unsignedChatContent)
    elseif message == nil and v.signedChatContent ~= nil then
        message = text_of(v.signedChatContent)
    end
    if v.networkName ~= nil then
        return "<" .. text_of(v.networkName) .. "> " .. tostring(message or "")
    end
    return message
end
summarizers.profileless_chat = function(v)
    return "<" .. text_of(v.name) .. "> " .. text_of(v.message)
end
summarizers.disguised_chat = summarizers.profileless_chat
summarizers.set_title_text = function(v) return text_of(v.text) end
summarizers.set_title_subtitle = summarizers.set_title_text
summarizers.action_bar = summarizers.set_title_text
summarizers.custom_payload = function(v) return v.channel end
summarizers.transfer = function(v) return tostring(v.host) .. ":" .. tostring(v.port) end
summarizers.server_info = function(v)
    local status = type(v.response) == "string" and json_decode(v.response)
    if type(status) ~= "table" then
        return nil
    end
    local parts = {}
    if type(status.version) == "table" then
        parts[#parts + 1] = tostring(status.version.name)
    end
    if type(status.players) == "table" then
        parts[#parts + 1] = string.format("%s/%s players", tostring(status.players.online), tostring(status.players.max))
    end
    if status.description ~= nil then
        parts[#parts + 1] = text_of(status.description)
    end
    return table.concat(parts, ", ")
end

local function summarize(name, values)
    if type(values) ~= "table" then
        return nil
    end
    local summarizer = summarizers[name]
    local ok, summary = true, nil
    if summarizer ~= nil then
        ok, summary = pcall(summarizer, values)
    else
        -- Coordinates of entity and block related packets
        summary = position_text(values.x, values.y, values.z)
        if summary == nil and type(values.location) == "table" then
            summary = position_text(values.location.x, values.location.y, values.location.z)
        end
    end
    if not ok or type(summary) ~= "string" or summary == "" then
        return nil
    end
    -- Formatting codes and line breaks
    summary = summary:gsub("\194\167.", ""):gsub("[\r\n]+", " ")
    if #summary > MAX_SUMMARY then
        summary = summary:sub(1, MAX_SUMMARY) .. "..."
    end
    return summary
end

---------------------------------------------------------------------------
-- Packet parsing
---------------------------------------------------------------------------

-- Each Wireshark Lua script has its own environment, share the parser through _G
local minecraft_native = {}
_G.minecraft_native = minecraft_native

minecraft_native.version_name = version_name

-- Parse one uncompressed packet (packet id + content)
-- Returns the packet name (nil if unknown), the parsed values and a short summary (nil if none)
function minecraft_native.dissect_packet(tvb, pinfo, tree, protocol_version, state, clientbound)
    local subtree = tree:add(minecraft, tvb(), "Minecraft (minecraft-data)")
    local definition, used_version, definition_name = get_definition(protocol_version)
    if definition == nil then
        subtree:add_proto_expert_info(ef.no_definition, "No minecraft-data definition for protocol " .. protocol_version)
        return nil
    end
    local definition_item = subtree:add(pf.definition, definition_name)
    definition_item:set_generated()
    if used_version ~= protocol_version then
        definition_item:add_proto_expert_info(ef.fallback,
            string.format("No definition for protocol %d, using the one of protocol %d (%s)", protocol_version, used_version, definition_name))
    end

    local state_key = state_keys[state]
    local state_definition = state_key and definition[state_key] and definition[state_key][clientbound and "toClient" or "toServer"]
    if state_definition == nil then
        subtree:add_proto_expert_info(ef.no_definition, "No definition for state " .. tostring(state))
        return nil
    end

    local types = state_definition.types
    local packet_fields = types.packet[2]
    local id_mapper = packet_fields[1].type[2]
    local params_switch = packet_fields[2].type[2]

    local r = new_reader(tvb, definition, types)
    local values = nil
    local name = nil
    local ok, err = pcall(function()
        local id = r:var(5)
        subtree:add(pf.packet_id, tvb(0, r.pos), id)
        name = lookup_mapping(id_mapper.mappings, id)
        if name == nil then
            subtree:add_proto_expert_info(ef.unknown_packet, string.format("Unknown packet id 0x%02X", id))
            return
        end
        subtree:add(pf.packet_name, name):set_generated()
        subtree:set_text(string.format("%s (0x%02X, %s, %s)", name, id, state_names[state], clientbound and "clientbound" or "serverbound"))
        values = r:read(params_switch.fields[name] or "void", nil, subtree, { [PARENT] = nil }, "", true)
        if values == nil then
            values = {}
        end
    end)
    if not ok then
        subtree:add_proto_expert_info(ef.error, tostring(err))
    elseif name ~= nil and r.pos < r.len then
        subtree:add(pf.data, tvb(r.pos, r.len - r.pos))
            :add_proto_expert_info(ef.leftover, string.format("%d byte(s) not covered by the definition", r.len - r.pos))
    end
    local summary = ok and summarize(name, values) or nil
    if summary ~= nil then
        subtree:add(pf.summary, summary):set_generated()
    end
    return name, values, summary
end

---------------------------------------------------------------------------
-- TCP dissector
---------------------------------------------------------------------------

local f_tcp_stream = Field.new("tcp.stream")

-- Connection state while dissecting the capture in order, per TCP stream
local connections = {}
-- State snapshot of each packet, so later (out of order) dissections give the same result
local packet_states = {}

local function new_connection()
    local protocol = minecraft.prefs.default_protocol
    if protocol == 0 then
        protocol = newest_protocol() or 0
    end
    return { state = STATE_HANDSHAKE, compression = -1, protocol = protocol, encrypted = false, handshake_seen = false }
end

-- Read a varint from a tvb, returns value, size (nil if incomplete, false if invalid)
local function peek_varint(tvb, offset)
    local value, shift = 0, 0
    for i = 0, 2 do
        if offset + i >= tvb:len() then
            return nil
        end
        local b = tvb(offset + i, 1):uint()
        value = value | ((b & 0x7F) << shift)
        if (b & 0x80) == 0 then
            return value, i + 1
        end
        shift = shift + 7
    end
    return false
end

-- The handshake is parsed manually since we don't know the protocol version yet
local function parse_handshake(tvb)
    local r = setmetatable({ tvb = tvb, pos = 0, len = tvb:len(), depth = 0 }, Reader)
    local ok, protocol, next_state = pcall(function()
        if r:var(5) ~= 0 then
            error("not a handshake", 0)
        end
        local protocol = r:var(5)
        local host_size = r:var(5)
        r:need(host_size + 2)
        r.pos = r.pos + host_size + 2
        return protocol, r:var(5)
    end)
    if ok then
        return protocol, next_state
    end
    return nil
end

local function update_connection(conn, name, values, clientbound)
    if conn.state == STATE_LOGIN then
        if clientbound and name == "compress" then
            conn.compression = values.threshold or conn.compression
        elseif not clientbound and name == "encryption_begin" then
            conn.encrypted = true
        elseif not clientbound and name == "login_acknowledged" then
            conn.state = STATE_CONFIGURATION
        elseif clientbound and name == "success" and conn.protocol < PROTOCOL_WITH_CONFIGURATION then
            conn.state = STATE_PLAY
        end
    elseif conn.state == STATE_CONFIGURATION then
        if not clientbound and name == "finish_configuration" then
            conn.state = STATE_PLAY
        end
    elseif conn.state == STATE_PLAY then
        if not clientbound and name == "configuration_acknowledged" then
            conn.state = STATE_CONFIGURATION
        end
    end
end

local function dissect_pdu(tvb, pinfo, tree, conn, key, clientbound, info)
    local snapshot = packet_states[key]
    if snapshot == nil then
        snapshot = { state = conn.state, compression = conn.compression, protocol = conn.protocol,
            encrypted = conn.encrypted, handshake_seen = conn.handshake_seen }
        packet_states[key] = snapshot
    end
    local first_pass = not pinfo.visited

    local subtree = tree:add(minecraft, tvb())
    local length, length_size = peek_varint(tvb, 0)
    subtree:add(pf.length, tvb(0, length_size), length)
    subtree:add(pf.state, snapshot.state):set_generated()
    subtree:add(pf.direction, clientbound and "clientbound" or "serverbound"):set_generated()
    subtree:add(pf.protocol_version, snapshot.protocol):set_generated()
    -- (unless this packet is the handshake)
    if not snapshot.handshake_seen and not (snapshot.state == STATE_HANDSHAKE and not clientbound) then
        subtree:add_proto_expert_info(ef.no_handshake)
    end

    local body = tvb(length_size, tvb:len() - length_size)
    if snapshot.compression >= 0 then
        local r = setmetatable({ tvb = tvb, pos = length_size, len = tvb:len(), depth = 0 }, Reader)
        local ok, data_length = pcall(Reader.var, r, 5)
        if not ok then
            subtree:add_proto_expert_info(ef.error, "Invalid compressed packet")
            return
        end
        subtree:add(pf.data_length, tvb(length_size, r.pos - length_size), data_length)
        if data_length > 0 then
            body = tvb(r.pos, tvb:len() - r.pos):uncompress_zlib("Decompressed packet")
            if body == nil then
                subtree:add_proto_expert_info(ef.error, "Decompression failed")
                return
            end
        elseif r.pos < tvb:len() then
            body = tvb(r.pos, tvb:len() - r.pos)
        else
            body = nil
        end
    end
    if body == nil then
        subtree:add_proto_expert_info(ef.error, "Empty packet")
        return
    end

    local name, values, summary
    if snapshot.state == STATE_HANDSHAKE and not clientbound then
        local body_tvb = body:tvb()
        local protocol, next_state = parse_handshake(body_tvb)
        if first_pass and protocol ~= nil then
            conn.protocol = protocol
            conn.handshake_seen = true
            conn.state = next_state == 1 and STATE_STATUS or STATE_LOGIN
        end
        name, values, summary = minecraft_native.dissect_packet(body_tvb, pinfo, subtree, protocol or snapshot.protocol, STATE_HANDSHAKE, false)
    else
        name, values, summary = minecraft_native.dissect_packet(body:tvb(), pinfo, subtree, snapshot.protocol, snapshot.state, clientbound)
        if first_pass and name ~= nil then
            update_connection(conn, name, values or {}, clientbound)
        end
    end
    subtree:set_text(string.format("Minecraft %s (%s)", name or "packet", state_names[snapshot.state]))
    info[#info + 1] = (name or "?") .. (summary and (": " .. summary) or "")
end

function minecraft.dissector(tvb, pinfo, tree)
    local stream_field = f_tcp_stream()
    local stream = stream_field and stream_field.value or -1
    local conn = connections[stream]
    if conn == nil then
        conn = new_connection()
        connections[stream] = conn
    end
    local clientbound = pinfo.src_port == pinfo.match_uint
    local frame_key = pinfo.number .. ":" .. (clientbound and "c" or "s")

    pinfo.cols.protocol:set("Minecraft")

    -- Once encrypted, packet boundaries can't be found anymore
    local encrypted = packet_states[frame_key .. ":encrypted"]
    if encrypted == nil then
        encrypted = conn.encrypted
        packet_states[frame_key .. ":encrypted"] = encrypted
    end
    if encrypted then
        local item = tree:add(minecraft, tvb())
        item:add(pf.data, tvb())
        item:add_proto_expert_info(ef.encrypted)
        pinfo.cols.info:set(string.format("%s Encrypted data", clientbound and "S → C" or "C → S"))
        return tvb:len()
    end

    local offset, index, info = 0, 0, {}
    local length = tvb:len()
    while offset < length do
        local size, size_length = peek_varint(tvb, offset)
        if size == false then
            tree:add(minecraft, tvb(offset)):add_proto_expert_info(ef.error, "Invalid packet length")
            break
        end
        if size == nil or offset + size_length + size > length then
            pinfo.desegment_offset = offset
            pinfo.desegment_len = size == nil and DESEGMENT_ONE_MORE_SEGMENT or (offset + size_length + size - length)
            break
        end
        dissect_pdu(tvb(offset, size_length + size):tvb(), pinfo, tree, conn, frame_key .. ":" .. index, clientbound, info)
        offset = offset + size_length + size
        index = index + 1
    end

    if #info > 0 then
        local snapshot = packet_states[frame_key .. ":0"]
        local shown = table.concat(info, ", ", 1, math.min(#info, 8)) .. (#info > 8 and string.format(", ... (%d packets)", #info) or "")
        pinfo.cols.info:set(string.format("%s [%s] %s", clientbound and "S → C" or "C → S",
            snapshot and state_names[snapshot.state] or "?", shown))
    end
    return length
end

function minecraft.init()
    connections = {}
    packet_states = {}
end

local registered_ports = nil

local function register_ports()
    local tcp_port = DissectorTable.get("tcp.port")
    if registered_ports ~= nil then
        tcp_port:remove(registered_ports, minecraft)
    end
    registered_ports = minecraft.prefs.ports
    if registered_ports ~= nil and registered_ports ~= "" then
        tcp_port:add(registered_ports, minecraft)
    end
end

function minecraft.prefs_changed()
    if registered_ports ~= minecraft.prefs.ports then
        register_ports()
    end
end

register_ports()
DissectorTable.get("tcp.port"):add_for_decode_as(minecraft)
