#!/usr/bin/env python3
"""Generate the protocol definitions used by wireshark/minecraft.lua.

Reads the protocol.json files of PrismarineJS/minecraft-data and writes them as Lua
tables in wireshark/minecraft_mcdata/:
  - <data path>.mcdata  one file per distinct protocol definition (e.g. 1.21.9.mcdata)
  - index.mcdata        protocol version number -> definition file and game versions

The files don't use the .lua extension so Wireshark doesn't load them all at startup,
minecraft.lua loads the one it needs on demand.

Usage:
  python tools/gen_mcdata.py                      # download from GitHub at the pinned commit
  python tools/gen_mcdata.py --source ../minecraft-data
  python tools/gen_mcdata.py --ref master --min-protocol 764
"""

import argparse
import json
import pathlib
import re
import urllib.request

# minecraft-data commit the definitions are generated from
DEFAULT_REF = "095709f3ad62b043069141dc127fc80ef6cd10fa"
RAW_URL = "https://raw.githubusercontent.com/PrismarineJS/minecraft-data/{ref}/data/{path}"
# 1.8, oldest version supported by SniffCraft
DEFAULT_MIN_PROTOCOL = 47


def load_json(source, ref, path):
    if source is not None:
        return json.loads((pathlib.Path(source) / "data" / path).read_text(encoding="utf-8"))
    with urllib.request.urlopen(RAW_URL.format(ref=ref, path=path)) as response:
        return json.load(response)


def lua_string(s):
    out = ['"']
    for c in s:
        if c == "\\":
            out.append("\\\\")
        elif c == '"':
            out.append('\\"')
        elif c == "\n":
            out.append("\\n")
        elif ord(c) < 32:
            out.append("\\%03d" % ord(c))
        else:
            out.append(c)
    out.append('"')
    return "".join(out)


def to_lua(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "nil"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, str):
        return lua_string(value)
    if isinstance(value, list):
        return "{" + ",".join(to_lua(v) for v in value) + "}"
    if isinstance(value, dict):
        return "{" + ",".join("[" + lua_string(k) + "]=" + to_lua(v) for k, v in value.items()) + "}"
    raise TypeError("Unsupported json value: %r" % (value,))


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--source", help="local minecraft-data checkout (default: download from GitHub)")
    parser.add_argument("--ref", default=DEFAULT_REF, help="minecraft-data git ref to download (default: %(default)s)")
    parser.add_argument("--min-protocol", type=int, default=DEFAULT_MIN_PROTOCOL, help="oldest protocol version to include (default: %(default)s)")
    parser.add_argument("--output", default=str(pathlib.Path(__file__).resolve().parent.parent / "wireshark" / "minecraft_mcdata"))
    args = parser.parse_args()

    data_paths = load_json(args.source, args.ref, "dataPaths.json")["pc"]
    protocol_versions = load_json(args.source, args.ref, "pc/common/protocolVersions.json")

    # protocolVersions.json is sorted newest first, keep the newest release for each protocol number
    protocols = {}
    # Protocol number -> game versions using it (also the ones without a definition yet), oldest first
    game_versions = {}
    for entry in protocol_versions:
        # Skip snapshots, pre-releases and release candidates, and versions before 1.7
        # (their protocol numbers were reused later, 1.4.2 is also protocol 47)
        if (not re.fullmatch(r"\d+\.\d+(\.\d+)?", entry["minecraftVersion"]) or entry["version"] < args.min_protocol
                or not entry.get("usesNetty", True)):
            continue
        game_versions.setdefault(entry["version"], []).insert(0, entry["minecraftVersion"])
        data_path = data_paths.get(entry["minecraftVersion"], {}).get("protocol")
        if data_path is not None and entry["version"] not in protocols:
            protocols[entry["version"]] = (data_path, entry["minecraftVersion"])

    output = pathlib.Path(args.output)
    output.mkdir(parents=True, exist_ok=True)
    for old in output.glob("*.mcdata"):
        old.unlink()

    index = {}
    for protocol, (data_path, minecraft_version) in sorted(protocols.items()):
        name = data_path.split("/")[-1]
        index[protocol] = name
        target = output / (name + ".mcdata")
        if target.exists():
            continue
        definition = load_json(args.source, args.ref, data_path + "/protocol.json")
        target.write_text(
            "-- Generated by tools/gen_mcdata.py from minecraft-data " + args.ref + " (" + data_path + "), do not edit\n"
            "return " + to_lua(definition) + "\n",
            encoding="utf-8", newline="\n")
        print("%s (protocol %d, Minecraft %s)" % (target.name, protocol, minecraft_version))

    lines = ["-- Generated by tools/gen_mcdata.py from minecraft-data " + args.ref + ", do not edit", "return {", "    protocols = {"]
    lines += ["        [%d] = %s," % (protocol, lua_string(name)) for protocol, name in sorted(index.items())]
    lines += ["    },", "    -- Game versions of each protocol number, for display", "    versions = {"]
    lines += ["        [%d] = %s," % (protocol, lua_string(names[0] if len(names) == 1 else names[0] + " - " + names[-1]))
              for protocol, names in sorted(game_versions.items())]
    lines += ["    },", "}", ""]
    (output / "index.mcdata").write_text("\n".join(lines), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
